### PR TITLE
add a simple regression example

### PR DESCRIPTION
**Pull request by dragonfly90**
Add a simple regression example for SAS Viya, the data is generated randomly and uploaded to server

Liang Dong

### CODE REVIEW

**Comment by kesmit13** [comment]
- Add some descriptive text to the top of the notebook so we know what it is

In [1]:
- Remove the importlib stuff at the top
- Remove sys.path.append(…)

In [3-4]:
- Use generic hostname and standard port number (5570)
- Use casdata = casconn.upload_frame(data) and no explicit CASTable(…) in In[3]

In [7-]:
- Maybe a short explanation of what’s going on in this section

In[11]:
- I’d just remove this since it’s not generic between backends

In[15]:
- Short description of whats going on in this section

In[16]:
- Probably don’t need this since the help information won’t show up in the example notebook anyway.

In[20]:
- Don’t use n_jobs= unless you are going to promote the table.  It has no effect if the table is session local.

- Can we also show SAS 9 working at the end?  Not a full explanation, just quickly load the data and use the same dtree and hpt objects being applied to the SAS 9 data sets.

**Comment by dragonfly90** [comment]
@kesmit13 I fixed issues except the sas9 example, there seems to be a bug there. Thank you.

**Comment by dragonfly90** [comment]
@kesmit13, Jared found it is not a bug but the format issue. I will update it later.

**Comment by dragonfly90** [comment]
@kesmit13 I added sas 9 version, it works. Could you check it?

**Pull request merged**
